export const AHA_REQUEST_ID = "aha-request-id";

export const INVALID_AUTH_TOKEN = "INVALID_AUTH_TOKEN";
export const INVALID_CURRENT_PASSWORD = "INVALID_CURRENT_PASSWORD";
export const INVALID_SESSION_TOKEN = "INVALID_SESSION_TOKEN";
export const PASSWORD_HAS_ALREADY_BEEN_SET = "PASSWORD_HAS_ALREADY_BEEN_SET";
export const PASSWORD_UPDATE_NOT_ALLOWED = "PASSWORD_UPDATE_NOT_ALLOWED";
export const SESSION_NOT_FOUND = "SESSION_NOT_FOUND";
export const SESSION_TOKEN_EXPIRED = "SESSION_TOKEN_EXPIRED";
export const SESSION_TOKEN_NOT_PROVIDED = "SESSION_TOKEN_NOT_PROVIDED";
export const UNABLE_TO_REVOKE_CURRENT_SESSION =
  "UNABLE_TO_REVOKE_CURRENT_SESSION";
